### ISSUE TITLE
Stop sending message to Slack each time... 

### ISSUE THREAD

**Issue by lisad** [dtinit/portmap#119]
I set up the slack forward initially to just be confident that the site was working and notice if it was getting used. Now that it's used regularly, we should disable that. 

To replace this with something that allows us to know what's going on, I welcome suggestions...

**Comment by alexbainter** [comment]
This is easy to remove (just these lines): https://github.com/dtinit/portmap/blob/d5532e4fdedc272c2982e79c04cfeed3d21572f5/portmap/core/views.py#L170-L174

I think the [analytics page](https://portmap.dtinit.org/dj-admin/analytics) might work as a replacement already since we can see all the query stats. We could add charts with a time dimension too, for queries over time/etc.
