### ISSUE TITLE
Fix invalid source/destination combinations with no articles being selectable

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portmap#18]
We shouldn't be able to get into this state:
![Screenshot from 2024-02-20 11-35-22](https://github.com/dtinit/portmap/assets/6510436/48f1da77-2495-4a9b-8d0d-c189bfcd29e6)

## Steps to recreate
1. Choose "Text Social Media"
2. For the source, choose "Facebook"
3. For the destination, choose any option
4. Press "Find Articles"

## Expected result
- If a data type category has no articles, it shouldn't be an option
- If a source/destination combination has no articles, it shouldn't be possible to select it
- If articles for these combinations really do exist, they should be displayed

(Not sure which of these three scenarios we're in, or maybe it's something else. Maybe the articles exist but don't have metadata formatted properly?)

## Actual result
An empty article list is displayed.

**Comment by aaronjae22** [comment]
I'll be working on it.

**Comment by alexbainter** [comment]
@aaronjae22 If this turns out to be a frontend/JS issue feel free to send it back to me!

**Comment by aaronjae22** [comment]
Sure. If you need anything please let me know. Thanks

**Comment by alexbainter** [comment]
@aaronjae22 Wait so is this a frontend issue? I didn't meant to indicate that it was (I haven't looked into it at all!)

**Comment by aaronjae22** [comment]
I misread the comment. Sorry. I'll continue on it and let you know about it.

**Comment by alexbainter** [comment]
No worries! Found another combination with this behavior: Book History > Goodreads --> The StoryGraph

**Comment by aaronjae22** [comment]
There's a couple of ways we could address this situation.

**1.** We could disable the combinations that doesn't have any articles yet. For example, if we select Facebook in the 'Where is it now?' dropdown, the 'Destination' dropdown will only show the ones that have articles.

<img width="410" alt="image" src="https://github.com/dtinit/portmap/assets/71613005/cc95cf0b-5917-4534-ac8a-a69d39d84570">

The problem is that since we will not display the articles page, we won't be able to give the users the opportunity to give feedback or give something that could work for us.

<img width="729" alt="image" src="https://github.com/dtinit/portmap/assets/71613005/c382a128-6008-40ba-b64f-ba665e98c9e7">

**2.** Second solution would be display some sort of 404 page but give the users the chance of give feedback. Something similar to what we have now but display something else when articles aren't found.

**3.** Third would be use an UX Feedback Messaging when selecting an option from the 'Destination' dropdown that doesn't have articles in it. But again, this won't give the user the chance of give feedback and I believe this is an important feature that could be very useful in the near future.

![image](https://github.com/dtinit/portmap/assets/71613005/64735b0d-7987-4700-859f-f36707fc6a3e)

I'm open to suggestions about what would work best for us.

**Comment by aaronjae22** [comment]
Given what @alexbainter said in the **Expected Result** section I think that probably the best solution would be that if a data type category has no articles, it shouldn't be an option.

**Comment by lisad** [comment]
The original intent was that if there's no article for a given type/source/destination combination, then that destination shouldn't appear in the dropdown after the type/source are selected.  I expect it was probably a bug in the backend that put an invalid destination in the list associated with a type and a source, (the data for the form that's passed to the front page) but it might in fact be that the data passed is correct and the front page logic uses it incorrectly. 

We do have an opportunity for the user to give feedback on the front page anyway, so I hope that works for folks
